name: Release

on:
  push:
    branches:
      - master # For stable releases
      - next # For pre-releases

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Cache pnpm
        uses: pnpm/action@v4


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: npm i

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release